### ISSUE TITLE
Seems to not work with multiple plugins using the loafmenus system.

### ISSUE THREAD

**Issue by ashfn** [FigT/LoafMenus#2]

**Comment by FigT** [comment]
Can you elaborate? It should work fine

**Comment by ashfn** [comment]
When I have two different plugins using LoafMenus, the second plugin to load has an error registering the LoafMenuRegustrar, in both plugins I use this `loafMenuRegistrar = new LoafMenuRegistrar(this);`

**Comment by FigT** [comment]
> When I have two different plugins using LoafMenus, the second plugin to load has an error registering the LoafMenuRegustrar, in both plugins I use this `loafMenuRegistrar = new LoafMenuRegistrar(this);`

Can you send the full error (or your `latest.log`) in a [Pastebin](https://pastebin.com) please?

**Comment by ashfn** [comment]
Sure, https://pastebin.com/BHy8UxY1

**Comment by FigT** [comment]
Ah, when shading LoafMenus, try relocating it. 

[if you’re using Maven & the shade plugin, read this example](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html)
[if you’re using Gradle & the shadow plugin, read this example](https://imperceptiblethoughts.com/shadow/configuration/relocation)


*I eventually will overhaul this, and make it easier to initialize with multiple plugins.*

**Comment by ashfn** [comment]
ok, thanks

**Comment by ashfn** [comment]
Do you think you could provide an example? Sorry I'm just having difficulties getting it working that way

**Comment by FigT** [comment]
> Do you think you could provide an example?

I provided some above, but if you want, you can send your `pom.xml` or `build.gradle` (or other if you use a different dependency management system) in a Pastebin, and I can modify it myself.

**Comment by ashfn** [comment]
Thanks, https://pastebin.com/6XpnejrU

**Comment by FigT** [comment]
No problem. https://pastebin.com/HDedE7DD (remember to add the relocation to all of your plugins' poms)

Let me know if you have any more problems.

**Comment by ashfn** [comment]
thank you so much

**Comment by ashfn** [comment]
~~So if I have two plugins using loafmenus it wont work with only one of them doing relocation?~~

EDIT: got it all working, thank you so much for helping out, you have saved me from having to redo so much work :smile:
